### PR TITLE
Allow to access results of the response document

### PR DESCRIPTION
**Pull request by Exelord**
Hi @lgebhardt,
I added the results of `process_request` to an instance variable. Thanks to that we can write better controllers tests using assertions with `resource` instances instead of parsing JSON string.

### CODE REVIEW

**Comment by lgebhardt** [comment]
@Exelord I agree that exposing the results is an improvement, but it conflicts with the multiple operations work I'm in the middle of. This requires each operation to be serialized after processing so subsequent operations can use JSON pointers to the prior results.

**Comment by Exelord** [comment]
Hi @lgebhardt,
I applied the implementation to the current master, what do you think about it now?

**Comment by Exelord** [comment]
ping?

**Comment by lgebhardt** [comment]
I'm still waiting for some clarity on the operations direction. I don't want to merge if it's going to create issues down the road. But I think it's likely we won't be using json pointers, so I can possibly restructure #951.

**Pull request closed without merging**
