### PR TITLE
Remove rails as dependency

### PR DESCRIPTION
**Pull request by quinn**
(this is a work in process probably...)
- remove 'rails/all' from test helper
- vender minitest-spec-rails
- add activerecord and railties to gemspec

### CODE REVIEW

**Comment by lgebhardt** [comment]
Thanks. I'd like to avoid needing to vendor minitest-spec-rails. Without it the tests seem to pass for rails 5, but not 4.2.

**Comment by quinn** [comment]
@lgebhardt yeah that's reasonable. I wanted to confirm that nothing would break in the test suite if the other parts of rails were included (even after removing rails, it was all still being pulled in by minitest-spec-rails). 

Not sure what you mean by "without it", but I'll push again with the vendored stuff removed and add back into the gemspec

**Comment by quinn** [comment]
(i tested again on 4.2 as well)

**Comment by quinn** [comment]
@lgebhardt pushed. I'll squash these when it's ready.

**Comment by lgebhardt** [comment]
Thanks. Looks ready to squash to me.

**Comment by quinn** [comment]
@lgebhardt ok cool, done.

**Comment by lgebhardt** [comment]
@quinn Thanks!

**Comment by evolve2k** [comment]
Nice work folks :)

**Comment by konk303** [comment]
why updated dependency of activerecord/railties to 4.1 instead of 4.0 ? 😢 
any particular reason?

I am using rails4.0 and noticed I couldn't update to 0.9.0.

using unsupported old rails is absolutely my bad I understand,
want to know if there is stg actually doesn't work with rails4.0

**Pull request merged**
