### PR TITLE
Fix foreign filter lookups

### PR DESCRIPTION
**Pull request by DavidMikeSimon**
Two bugs related to filtering on relationships in jsonapi-resources are addressed by this PR:
- Singular relationships with `:foreign_key_on => :related` cannot be filtered on
- Relationships to associations that have a name different from the name of the target table (e.g. `has_many :friends` referencing a `people` table) also cannot be filtered on

The PR changes `Resource#apply_filters` to fix these and also adds regression tests.

Also, some invalid unused associations are removed from the test fixtures.

### CODE REVIEW

**Comment by DavidMikeSimon** [comment]
@lgebhardt Anything else I should do to get this PR ready to merge?

**Comment by lgebhardt** [comment]
@DavidMikeSimon Sorry for the delay in looking into this. I'll review it soon and let you know.

**Comment by lgebhardt** [comment]
@DavidMikeSimon Could you please rebase against master. Sorry for stepping on your code.

**Comment by DavidMikeSimon** [comment]
@lgebhardt Okay, rebased. No worries, it was only a very slight conflict in the test fixture.

**Comment by DavidMikeSimon** [comment]
@lgebhardt Bump.

**Comment by lgebhardt** [comment]
@DavidMikeSimon Thanks! Sorry for the delay getting this merged.

**Pull request merged**
