### PR TITLE
Check for linkage key in associations [Issues #134 and #115]

### PR DESCRIPTION
**Pull request by sirvine**
Possible fix for https://github.com/cerebris/jsonapi-resources/issues/134 and https://github.com/cerebris/jsonapi-resources/issues/115.  Steps into "linkage" key, where available.

### CODE REVIEW

**Comment by fotinakis** [comment]
+1 for fixing this, going to patch this in for myself locally for now.

**Comment by lgebhardt** [comment]
Thanks for addressing this. However the spec is now requiring `linkage` for updates and creates. These changes do not enforce that new requirement, but rather supports both versions, which isn't correct.

Would you like to update this PR, including the tests, to enforce this? If not, I can get to it soon.

**Comment by sirvine** [comment]
Great point. I'll work on this, although I'm no expert on the JSONAPI spec. Is there a changelog for the spec somewhere that I can use to enforce the changes that don't affect my app (yet)?

**Comment by sirvine** [comment]
OK – updated tests, and added a check for a blank array in place of `linkage` key (i.e., where update is to clear linked objects).  Let me know if you want me to make any changes.

**Pull request merged**
