### PR TITLE
Jsonapi rc2

### PR DESCRIPTION
**Pull request by lgebhardt**
This is a big set of changes that start to bring JSONAPI-Resources into compliance with JSONAPI RC2. I'd like to get these merged in order to both have example application to use with the new JSONAPI spec, and so we can create issues against the master branch to track work yet to be done.

I'm not going to document the format changes here that needed to take place to meet the new spec, since those are spelled out in the JSONAPI update. Below are the major new features, besides formatting, that have been added:
- Pagination has been added through the use of Paginators. Two paginators have been provided to support offset and paged pagination. Custom paginators can also be created.
- Sorting has been changed to use the required direction (`+` or `-`). This led to a minor rework of the sort logic.
- Serializer options are now provided in the initializer and the serialization methods simply provide the objects to serialize. This allowed for dryer code between the new `serialize_to_links_hash` and `serialize_to_hash` methods. The controller is also, I hope, a bit clearer since this has been separated.
- Serializer now emits generated urls for associations and associated resources, based on a base url. This assumes the creation of routes for each related resource in the primary resource's namespace.
- `CreateHasOneAssociationOperation` operation has been removed along with `create_has_one_link` resource method.
- Request parsing has been cleaned up. Now makes more use of Strong Parameters (still more work to go though).
- `id` and `ids` special handling in `request` has been removed.
- Related resources may now be fetched. This has new routes and controller methods.

### CODE REVIEW

**Comment by barelyknown** [comment]
Great work on this. I've been using the branch on a new app and it's gone well.

**Comment by dgeb** [comment]
@barelyknown glad it's going well!

Merging now, even though there are a few (minor) aspects that are out of compliance. We'll open up issues soon to highlight these.

**Comment by xdmx** [comment]
Awesome work :+1: 

May I suggest you to keep a changelog directly in the repository and update it directly with important commits? That may help everyone to know what has been released and what to expect from the next version (like http://keepachangelog.com/ )

**Comment by dgeb** [comment]
@xdmx We are going to maintain release notes from now on: https://github.com/cerebris/jsonapi-resources/releases

And we'll try to maintain a list of upcoming features as issues: https://github.com/cerebris/jsonapi-resources/issues

Granted, release notes could be improved with more links to commits, and the issue tracker could be improved with better tagging, but we're trying.

**Pull request merged**
