### PR TITLE
Meta: page_count

### LINKED ISSUE #126: Pagination: total record/page count in meta
My Ember apps use sparse arrays to load visible data on demand. The sparse array needs some means for determining the total number of objects available to show. This allows my colleagues and I to fake the array length property with record counts provided by the server and, for example, draw an appropriately tall scrolling `<div>` to mimic the appearance of a single, continuous listing.

JSON API spec suggests using the top-level `links` object to include URLs for the first, last, next, and previous available pages. But offers no suggestions for where to provide a document count. My instinct suggests sending this data in the `meta` object. After all, the record count is not necessarily useful for every app or api.

I am guessing JR first needs to support the meta object (see #89) before addressing this need. I am opening this issue for future discussion since it is something critical to the apps I work on.

### PR DESCRIPTION
**Pull request by utilityboy**
Added option for top level `page_count` meta for paged paginators in addition to the record_count.

A number of client-side paging libraries look for APIs to return a total page count.

Potential closes #126?

### CODE REVIEW

**Comment by utilityboy** [comment]
@lgebhardt or @barelyknown is there anything else I can do here?

**Comment by lgebhardt** [comment]
@utilityboy Sorry for the very late response. I swear I commented about this back in March, but I probably forgot to hit the comment button. Anyway, it's missing tests that cover the page count in the find operation. You can see coverage with:

``` bash
COVERAGE=true bundle exec rake test
```

In addition the README needs to be updated for the configuration options.

**Comment by utilityboy** [comment]
No problem @lgebhardt.  I'll get on it this weekend.  Thanks for the update.

**Comment by utilityboy** [comment]
All set @lgebhardt.  Let me know if there's anything else.

**Comment by lgebhardt** [comment]
@utilityboy Thanks! Should be quite useful.

**Pull request merged**
