### PR TITLE
Allow 'href' and 'link' as field names

### PR DESCRIPTION
**Pull request by ggordon**
Allow 'href' and 'link' as fields names. Also add test relationships named 'type' or 'id'.

### CODE REVIEW

**Comment by lgebhardt** [comment]
I was actually going to look into whether we could get rid of the reserved field names. I know we need to keep `type` reserved, but I think we can now allow `href` and `links` since we moved all the attributes and relationships under the `attributes` and `relationships` keys.

**Comment by ggordon** [comment]
Let me know what you'd like to do, I was initially just trying to get rid of the deprecation warnings during testing.

**Comment by lgebhardt** [comment]
That would be nice to get rid of the warnings. I assume there's also a simple way of turning off the deprecation warnings, but I've learned to ignore them. 

If you're up for it you could remove the reserver fields except for type, add a test using them and see if it breaks.

**Comment by ggordon** [comment]
@lgebhardt I think this addresses your comment. Please let me know if I misinterpreted something.

**Comment by lgebhardt** [comment]
@ggordon Thanks again!

Merged by #510.

**Pull request closed without merging**
