### PR TITLE
Resource linkage

### LINKED ISSUE #299: why relationships for has_one association have data inside?
``` ruby
jsonapi_resources :authors do
    jsonapi_relationships
    jsonapi_resources :posts
    jsonapi_resources :comments
  end
```

``` ruby
class AuthorResource < JSONAPI::Resource
  has_one :author_detail
  has_one :author_type
  has_many :posts
  has_many :comments
end
```

`Started GET "/authors/1"`

``` ruby
{
    :data => {
                   "id" => "1",
                 "type" => "authors",
                "links" => {
            :self => "http://127.0.0.1:3000/authors/1"
        },
           "attributes" => {
                   "name" => "john",
               "username" => "johny",
              "is_active" => true,
            "description" => nil,
             "created_at" => Wed, 08 Jul 2015 20:22:40 UTC +00:00
        },
        "relationships" => {
            "author_detail" => {
                :links => {
                       :self => "http://127.0.0.1:3000/authors/1/relationships/author_detail",
                    :related => "http://127.0.0.1:3000/authors/1/author_detail"
                },
                 :data => {
                    :type => "author_details",
                      :id => "1"
                }
            },
              "author_type" => {
                :links => {
                       :self => "http://127.0.0.1:3000/authors/1/relationships/author_type",
                    :related => "http://127.0.0.1:3000/authors/1/author_type"
                },
                 :data => {
                    :type => "author_types",
                      :id => "1"
                }
            },
                    "posts" => {
                :links => {
                       :self => "http://127.0.0.1:3000/authors/1/relationships/posts",
                    :related => "http://127.0.0.1:3000/authors/1/posts"
                }
            },
                 "comments" => {
                :links => {
                       :self => "http://127.0.0.1:3000/authors/1/relationships/comments",
                    :related => "http://127.0.0.1:3000/authors/1/comments"
                }
            }
        }
    }
}
```

i thought that according to [documentation](http://jsonapi.org/format/#fetching-relationships) relationships should have data hash only when you include this relation or fetching data using related link like `http://127.0.0.1:3000/authors/1/relationships/author_type`

### PR DESCRIPTION
**Pull request by lgebhardt**
Adds option for outputting resource linkage outside of a compound document. Can be global configuration setting, or an a per association basis.

Exposed and fixes issues with single table inheritance polymorphism.

Fixes #299

### CODE REVIEW

**Comment by barelyknown** [comment]
Nice feature, @lgebhardt.

**Comment by lgebhardt** [comment]
@barelyknown thanks. It came about from #299.

**Comment by dgeb** [comment]
Looks good, but I favor a name other than `force_resource_linkage`. Perhaps `always_include_data` as I suggested in https://github.com/cerebris/jsonapi-resources/issues/299#issuecomment-119974462

The reason being that the concept of resource linkage applies to compound documents, and this option is specifically controlling the inclusion of data in non-compound documents.

**Comment by lgebhardt** [comment]
Just rebased this against master and squashed the commits.

**Comment by dgeb** [comment]
LGTM :shipit:

**Pull request merged**
