### PR TITLE
Cherrypicks into 0.9 - fixes #909 add possibility to set generic validation error

### LINKED ISSUE #909: ValidationErrors treats :base as an attribute and doesn't use details
Hi, 

 I would like to use the `error.detail` field to display customised errors messages for the front end. After some study, I'd like to explore some options of enhancement on ValidationErrors: 

**Attribute `:base` should be treated as the primary resource entity instead of an attribute**

Currently, `:base` is being treated as an attribute in source.point, e.g. `
"source": {
        "pointer": "/data/attributes/base"
      }
`. However, according to rails's doc at http://api.rubyonrails.org/classes/ActiveModel/Errors.html, "attribute should be set to :base if the error is not directly associated with a single attribute."  The `pointer` can be improved by pointing to `'/data'` as JSONAPI Spec's 'MAY' spec at http://jsonapi.org/format/#errors. And it will provide consistency with Rails as well.

**Will be be preferable if ValidationErrors use messages as detail with prefixing**

My reasoning is on JSONAPI spec's "MAY" recommendations on `title` and `detail` say: 

> - title: a short, human-readable summary of the problem that SHOULD NOT change from occurrence to occurrence of the problem, except for purposes of localization.
> - detail: a human-readable explanation specific to this occurrence of the problem. Like title, this field’s value can be localized.

It seems that rails's error messages behave more closely to JSONAPI Spec's `detail` as they allow dynamically use `%{value}`, `%{attribute}`, and `%{model}` to provide specifics to this occurrence. So JSONAPI spec's `detail` may just be rails's error message.  

However, in `ValidationErrors#json_api_error`, it prefixes the message with the attribute and a hyphen. This may be not always desirable as some, as in my case, would prefer to use their customized validation messages  as is for client facing UI. 

`detail: "#{format_key(attr_key)} - #{message}"`

Of course, we can just use the `title` as it is the error message as is at the moment. But it will slightly deviate from the `title`'s MAY recomendation. 

This can be even  taken  a step further to allow users to provide custmised ValidationErrors in `resource.rb` to define their user of the `title`, `detail`, `code` and other fields in JSONAPI Spec's error object. But that may take some futher elaboration. 

It will be nice to take them into consideration. 

Many thanks, 

Mytram

### PR DESCRIPTION
**Pull request by johnmosesman**
Context from gitter:

https://github.com/cerebris/jsonapi-resources/issues/909

image

image

### All Submissions:

- [x] I've checked to ensure there aren't other open [Pull Requests](https://github.com/cerebris/jsonapi-resources/pulls) for the same update/change.
- [ ] I've submitted a [ticket](https://github.com/cerebris/jsonapi-resources/issues) for my issue if one did not already exist.
- [x] My submission passes all tests. (Please run the full test suite locally to cut down on noise from travis failures.)
- [ ] I've used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message or the description.
- [ ] I've added/updated tests for this change.

### New Feature Submissions:

- [ ] I've submitted an issue that describes this feature, and received the go ahead from the maintainers.
- [ ] My submission includes new tests.
- [ ] My submission maintains compliance with [JSON:API](http://jsonapi.org/).

### Bug fixes and Changes to Core Features:

- [ ] I've included an explanation of what the changes do and why I'd like you to include them.
- [ ] I've provided test(s) that fails without the change.

### Reviewer Checklist:
- [ ] Maintains compliance with JSON:API
- [ ] Adequate test coverage exists to prevent regressions

### CODE REVIEW

**Comment by johnmosesman** [comment]
@lgebhardt

**Review by lgebhardt — APPROVED** [review]

**Comment by lgebhardt** [comment]
@johnmosesman Thanks!

**Comment by johnmosesman** [comment]
@lgebhardt Happy to help! What is the process for releasing the new version?

**Comment by lgebhardt** [comment]
I'll make a new release soon. Want to get one more thing in and also review other issues first.

**Comment by johnmosesman** [comment]
Great. Thank you!

**Pull request merged**
