### PR TITLE
Eager load includes for related resources (#1163)

### LINKED ISSUE #1163: Included resources are not eagerly fetched for #get_related_resources calls (v0.9.0)
## This issue is a (choose one):

- [x] Problem/bug report.
- [ ] Feature request.
- [ ] Request for support. **Note: Please try to avoid submitting issues for support requests. Use [Gitter](https://gitter.im/cerebris/jsonapi-resources) instead.** 

## Checklist before submitting:

- [x] I've searched for an existing issue.
- [ ] I've asked my question on [Gitter](https://gitter.im/cerebris/jsonapi-resources) and have not received a satisfactory answer.
- [x] I've included a complete [bug report template](https://github.com/cerebris/jsonapi-resources/blob/master/lib/bug_report_templates/rails_5_master.rb). This step helps us and allows us to see the bug without trying to reproduce the problem from your description. It helps you because you will frequently detect if it's a problem specific to your project.
- [x] The feature I'm asking for is compliant with the [JSON:API](http://jsonapi.org/) spec.

## Description

This bug applies specifically to the v0.9.0 version of the gem. Calls to the `#get_related_resources` action that use the `includes` URL parameter are resulting in N+1 queries to fetch the included records. The reason for this is because the `apply_includes` resource method is not being called in the relationship resource fetching logic (see the RelationshipBuilder class) as it does in the base resource fetching logic. The following bug report template provides a clear reproduction of this bug.

## Bug Report Template

```
begin
  require 'bundler/inline'
  require 'bundler'
rescue LoadError => e
  STDERR.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

gemfile(true, ui: ENV['SILENT'] ? Bundler::UI::Silent.new : Bundler::UI::Shell.new) do
  source 'https://rubygems.org'

  gem 'rails', require: false
  gem 'sqlite3', platform: :mri

#   gem 'activerecord-jdbcsqlite3-adapter'
  gem 'activerecord-jdbcsqlite3-adapter',
      git: 'https://github.com/jruby/activerecord-jdbc-adapter',
      branch: 'test-rails-5',
      platform: :jruby

  # This bug is specific to v0.9.0
  gem 'jsonapi-resources', "~> 0.9.0", require: false
  # if ENV['JSONAPI_RESOURCES_PATH']
  #   gem 'jsonapi-resources', path: ENV['JSONAPI_RESOURCES_PATH'], require: false
  # else
  #   gem 'jsonapi-resources', git: 'https://github.com/cerebris/jsonapi-resources', require: false
  # end

end

# prepare active_record database
require 'active_record'

class NullLogger < Logger
  def initialize(*_args)
  end

  def add(*_args, &_block)
  end
end

ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = ENV['SILENT'] ? NullLogger.new : Logger.new(STDOUT)
ActiveRecord::Migration.verbose = !ENV['SILENT']

ActiveRecord::Schema.define do
  # Add your schema here
  create_table :authors, force: true do |t|
    t.string :name
  end
  create_table :posts, force: true do |t|
    t.string :title
    t.belongs_to :author
  end
  create_table :comments, force: true do |t|
    t.string :content
    t.belongs_to :post
  end
end

# create models
class Author < ActiveRecord::Base
  has_many :posts
end
class Post < ActiveRecord::Base
  belongs_to :author
  has_many :comments
end
class Comment < ActiveRecord::Base
  belongs_to :post
end

# prepare rails app
require 'action_controller/railtie'
# require 'action_view/railtie'
require 'jsonapi-resources'

class ApplicationController < ActionController::Base
end

# prepare jsonapi resources and controllers
class AuthorsController < ApplicationController
  include JSONAPI::ActsAsResourceController
end
class PostsController < ApplicationController
  include JSONAPI::ActsAsResourceController
end
class CommentsController < ApplicationController
  include JSONAPI::ActsAsResourceController
end

class AuthorResource < JSONAPI::Resource
  attribute :name
  has_many :posts
end
class PostResource < JSONAPI::Resource
  attribute :title
  has_many :comments
end
class CommentResource < JSONAPI::Resource
  attribute :content
  has_one :post
end

class TestApp < Rails::Application
  config.root = File.dirname(__FILE__)
  config.logger = ENV['SILENT'] ? NullLogger.new : Logger.new(STDOUT)
  Rails.logger = config.logger

  secrets.secret_token = 'secret_token'
  secrets.secret_key_base = 'secret_key_base'

  config.eager_load = false
end

# initialize app
Rails.application.initialize!

JSONAPI.configure do |config|
  config.json_key_format = :underscored_key
  config.route_format = :underscored_key
end

# draw routes
Rails.application.routes.draw do
  jsonapi_resources :author, only: [:index, :create] do
    jsonapi_relationships only: :show
  end
  jsonapi_resources :post, only: [:index, :create, :show]
end

# prepare tests
require 'minitest/autorun'
require 'rack/test'

# Replace this with the code necessary to make your test fail.
class BugTest < Minitest::Test
  include Rack::Test::Methods

  def json_api_headers
    {'Accept' => JSONAPI::MEDIA_TYPE, 'CONTENT_TYPE' => JSONAPI::MEDIA_TYPE}
  end

  def test_fetch_related_resources_with_include
    author = Author.create! name: 'John Doe'
    10.times do |i|
      post = Post.create! title: "Post #{i + 1}", author: author
      Comment.create! content: "Comment #{i + 1}", post: post
    end

    get "/author/#{author.id}/posts?include=comments", nil, json_api_headers
    assert last_response.ok?
    json_response = JSON.parse(last_response.body)
    refute_nil json_response['data']
    refute_empty json_response['data']
    refute_empty json_response['data'].first
    assert author.id.to_s, json_response['data'].first['id']
    assert 'posts', json_response['data'].first['type']
    assert '11', json_response['included'].size

    puts <<-EOS
    =============================================================
    Review the query logs above and observe that the `comments`
    records were each fetch individually. Then add the following
    at line 62 of the RelationshipBuilder JR class and rerun
    the test:
    ```
    records = resource_klass.apply_includes(records, options)
    ```
    =============================================================
    EOS
  end

  private

  def app
    Rails.application
  end
end
```

### PR DESCRIPTION
**Pull request by hstrowd**
Fixes #1163 

Updates related resources fetching logic to eagerly load any relationships to be included in the response. This prevents the relationships for each of these records from being fetched individually.

### All Submissions:

- [x] I've checked to ensure there aren't other open [Pull Requests](https://github.com/cerebris/jsonapi-resources/pulls) for the same update/change.
- [x] I've submitted a [ticket](https://github.com/cerebris/jsonapi-resources/issues) for my issue if one did not already exist.
- [x] My submission passes all tests. (Please run the full test suite locally to cut down on noise from travis failures.)
- [x] I've used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message or the description.
- [x] I've added/updated tests for this change.

### New Feature Submissions:

- [ ] I've submitted an issue that describes this feature, and received the go ahead from the maintainers.
- [ ] My submission includes new tests.
- [ ] My submission maintains compliance with [JSON:API](http://jsonapi.org/).

### Bug fixes and Changes to Core Features:

- [x] I've included an explanation of what the changes do and why I'd like you to include them.
- [x] I've provided test(s) that fails without the change.

### Test Plan:

Not sure if I'm intended to fill this section out but my recommendation would be to setup an API that has a variety of relationship chains and verify that fetching related resources with an included relationship does not result in N+1 queries being triggered. It would also be worthwhile to test for regressions in all other association related API requests.

### Reviewer Checklist:
- [ ] Maintains compliance with JSON:API
- [ ] Adequate test coverage exists to prevent regressions

### CODE REVIEW

**Comment by senid231** [comment]
Hi @hstrowd 
you can add [bullet](https://github.com/flyerhzm/bullet) to test whether N+1 sql requests appear or not

**Review by lgebhardt — CHANGES_REQUESTED** [review]
@hstrowd Thanks for reporting and fixing this! Could you please pair this PR down to just the changes that are needed for the fix? Specifically the `relationship_builder.rb` change and the new tests. There's an existing method being used to count queries (see https://github.com/cerebris/jsonapi-resources/blob/87db4483d387b68e02fef8a16f39af8adb6134f9/test/controllers/controller_test.rb#L258) and I rather keep using this until we do a separate PR to replace the query counting logic. Same with fixing the `assert_nil` cleanup and bumping the versions (which is done as part of the release process).

**Comment by hstrowd** [comment]
@lgebhardt Thanks for the feedback. Will do.

**Comment by hstrowd** [comment]
Sorry for the delay in following up on this. I will try to get to it later this week. I have not forgotten.

**Comment by hstrowd** [comment]
I made the requested changes. I'll keep an eye on the CI build to ensure in passes. Don't hesitate to let me know if any additional work is needed here. Thanks.

**Comment by Subtletree** [comment]
@hstrowd This looks really good! Anything I can help with to get this across the line?

**Comment by hstrowd** [comment]
@Subtletree Thanks for checking in on this. When I ran the tests locally everything seemed to pass, but the build test failures are the exact tests that I introduced to cover this functionality. It seems like there may be something about the existing query counting logic that I'm not using correctly and is resulting in intermittent failures. I haven't had a chance to come back in and dive through it and at the moment I'll be travelling for the next ~3 weeks so I doubt I will during this time frame. I'll try to take a look into it shortly after I return but if you have the time and interest, feel free to take a look. Thanks!

**Comment by dgeb** [comment]
Merged via #1171 

Thanks @hstrowd!

**Pull request closed without merging**
