### PR TITLE
Catch LoadError when checkin for engine

### PR DESCRIPTION
**Pull request by gnfisher**
resolves issue #450, solution from @alessandro1997 comment in discussion.

### CODE REVIEW

**Comment by gnfisher** [comment]
This is an autoloader issue. The Rails guide covers it [here](http://guides.rubyonrails.org/autoloading_and_reloading_constants.html#autoloading-algorithms). There may be another way to check if the controller is from an Engine or not without relying on LoadError to be thrown (going to look into this) but as the code stands, just wrapping this in a begin/rescue to catch it should be fine. If the controller is part of an engine, the proper engine paths and urls are formatted, and if not, the expected LoadError from the Rails autoloader is caught and non engine paths and urls are formatted.

Should I look for an alternative way to handle the Engine check, or is this above solution acceptable?

**Comment by lgebhardt** [comment]
@gnfisher In general I'd like to avoid exceptions for flow control, however if raising `LoadError` is the way rails handles this I don't see a problem with your solution.

This passes the existing tests. I haven't looked into writing a test that confirms that this fixes the problem in #450. Is that something you could add? If it's not easy I can try to confirm using the steps in #450.

**Comment by gnfisher** [comment]
When following the steps ins #450 no LoadError was raised, and the response processed correctly. I can look into writing a test for it - the current ones didn't catch the problem so perhaps there's a little retooling I can do to the existing suite to fix that. I will also do a bit of poking around for a solution that doesn't depend on catching Rails autloader's LoadError.

**Comment by gnfisher** [comment]
I've been unable to craft a test for this. Somehow we'd have to use Rails autoloader to load the MyEngine and ApiV2Engine modules and their Engine classes... Admittedly I've not had a ton of time to put into this. If you could point me in a good direction I would be happy to look for a way to get this covered by the unit test.

**Comment by lgebhardt** [comment]
@gnfisher I'm not sure how to test for it either. Since it's not easy to test I've merged it into master. If we see no errors soon I'll cherry pick it into beta and maybe 0.8 as well if I can get a test figured out. 

Thanks for the fix and looking at the tests.

**Pull request merged**
