### PR TITLE
Public model_name_for_type method

### PR DESCRIPTION
**Pull request by Exelord**
Hi,
I just think this method could be used in many cases associated with polymorphic relations like filtering by polymorphic model type. In that case having this public could make it easier to implement.

### CODE REVIEW

**Comment by lgebhardt** [comment]
@Exelord Looking at it a little closer the method should probably be a class method and moved down to the `self` section. I should have caught that in #882. How about renaming it to something closer to `resource_type_for`, which is it's reciprocal, such as `model_name_for_type` or just `model_name_for`.

```ruby
  class << self
  #...
      def model_name_for_type(type)
        type_class_name = type.to_s.classify
        resource = resource_for(type_class_name)
        resource ? resource._model_name.to_s : type_class_name
      end
  end
```

**Comment by Exelord** [comment]
@lgebhardt You are right! I just forgot about moving it to `self`. I applied your feedback with method name and fixed tests :)

If u have more ideas or comment, go on!

Thanks :)

**Comment by lgebhardt** [comment]
@Exelord Thanks!

**Comment by toobulkeh** [comment]
How can this new feature be used?

Trying to see if it's something that can temporarily be used for #927

**Pull request merged**
