### PR TITLE
Remove support fetching multiple resources by id

### LINKED ISSUE #88: Remove support fetching multiple resources by id
JSON API RC2 removed support for GETting multiple resources by a comma delimited list of ids. We should remove this from JR as well.

### PR DESCRIPTION
**Pull request by sineed**
This PR resolves https://github.com/cerebris/jsonapi-resources/issues/88

@lgebhardt I have doubts about assertions of some tests.
For example, the test `test_tags_show_multiple_with_include` returns `200` only because of such behavior of `ActiveRecord` finder methods.

### CODE REVIEW

**Comment by lgebhardt** [comment]
@sineed, the assertions do seem a bit sketchy. I'm not sure how to best address that. I wonder if we should modify the `verify_key` method to assume and check for integer keys by default.

**Comment by sineed** [comment]
@lgebhardt I've made some changes. Please take a look if I understood you correctly

**Comment by lgebhardt** [comment]
That's what I had in mind. I think that's better than the way it was, though I wonder if there are any systems in common use that use strings for ids that we will break. UUIDs come to mind, though in my code where we use them I've already overridden the `verify_key` to enforce the format of UUIDs.

I want to leave this open for a day or two and see if anyone else has an opinion.

**Comment by sineed** [comment]
@lgebhardt agreed, the change can break resources with custom  `primary_key` and lack of custom logic in `verify_key`. So I think that it's necessary to mention in README.
Also rebased and squashed.

**Comment by dgeb** [comment]
I think this is fine for now, although I'd like to eventually add the concept of a "key type", which could then be referenced by `verify_key`. This would allow for cleaner and more consistent handling of UUIDs and custom key types.

**Comment by lgebhardt** [comment]
@sineed Thanks!

@dgeb I'll put an issue in for the "key type" concept.

**Pull request merged**
