### PR TITLE
Fix includes

### LINKED ISSUE #178: Inbetween nested join resource is being lost in `?include`
I just bumped in to this little gem. It's a bit tricky to explain so I'll just start with a few examples:
- `/list?include=x` - :+1: Includes `x`
- `/list?include=x.y` - :+1: Includes `y` (through `x`) 
- `/list?include=x,x.y` - :+1: Includes `x` and `y` (through `x`)
- `/list?include=x,x.y.z` - :+1: Includes `x` and `z` (through `y`, through `x`)
- `/list?include=x,x.y,x.y.z` - :-1: Includes `x` and `z` (through `y`, through `x`) but **not** `y` (through `x`) as I would have expected.

I'm guessing I get's lost somewhere in the AREL query or serialised away somehow but I just wanted to see if it's the expected results.

### PR DESCRIPTION
**Pull request by lgebhardt**
Fixes #178

### CODE REVIEW

**Comment by slaskis** [comment]
This is awesome, I tried it in my app and it works wonderfully!

**Comment by lgebhardt** [comment]
@slaskis Thanks for testing (and reporting) this.

**Comment by doctorloaf** [comment]
Where is the proper place to call in the serializer? I'm trying to include embedded resources within my resources but can not figure out the proper file to place the code in.

**Comment by lgebhardt** [comment]
@dopudesign The ResourceSerializer can be initialized with either the `include` or the `include_directives` options. If `include` is used it takes an array of include strings and these are converted to `IncludeDirectives` in the serializer.

Note that in master SerializerIncludeDirectives has been renamed to simply IncludeDirectives.

**Pull request merged**
