### PR TITLE
Adding total_count to meta data (optionally) to index response

### PR DESCRIPTION
**Pull request by bvandenbos**
Partial implementation for #126.  This allows a resource to opt-in to returning the total count in the meta data like so:

``` ruby
    class BookResource < JSONAPI::Resource
      attribute :title
      attribute :isbn

      include_total_count # tells the serializer to include total_count in meta

      has_many :book_comments
    end
```

I don't love this implementation, but wanted to get some feedback.  It wasn't clear where to start constructing the meta hash or what object should be responsible for issuing the query to get the total count.  Feels like there is a larger refactor that's trying to be born to accommodate meta (and probably links) in a broader sense.

### CODE REVIEW

**Comment by barelyknown** [comment]
Couple of comments:

1) I'd prefer the ability to set `include_total_count` to `true` or `false`, with `true` as the default argument.

``` ruby
  class BookResource < JSONAPI::Resource
    include_total_count false
  end
```

2) Can you add the ability to set a default configuration too? Something like:

``` ruby
JSONAPI.configure do |config|
  config.default_include_total_count = true
end
```

**Comment by bvandenbos** [comment]
Great feedback.  Both items added.

**Comment by slaskis** [comment]
I was looking for this myself, mainly to use for pagination. 

Maybe this API could be extended to a generic `meta` property? Something like this:

```
class BookResource < JSONAPI::Resource
  attribute :title
  attribute :isbn

  meta :total_count # tells the serializer to include total_count in meta

  has_many :book_comments
end
```

Which may allow adding other future properties as meta. However this may be confusing as to if it's a top-level meta or resource level meta when I think about it. Maybe not for this feature but others. These could be separated by defining class-methods (top-level) vs instance-methods (resource-level).

And it could also allow for setting options on the meta (simply passed in to the method). Something like this:

```
class BookResource < JSONAPI::Resource
  attribute :title
  attribute :isbn

  # as second argument (seems pretty rails to me)
  meta :total_count, filter: [:special_for_count]

  # or as a hash, which would allow for setting multiple meta at once
  meta total_count: {filter: [:special]}, other_meta: [:something]

  has_many :book_comments
end
```

What do you think? It seems to me these additions could easily be "plugins" by just being class or instance methods to be included into the resource in a module.

**Comment by bvandenbos** [comment]
In general, I like this approach, but we probably want to account for both top-level meta and resource-level meta.  `total_count` in this case would be a top-level meta entry.  The spec also allows "meta" at the entry level.  Something like this perhaps:

``` ruby
class BookResource < JSONAPI::Resource
  attribute :title
  attribute :isbn

  # Contrived resource-level meta example:
  meta :md5, -> { |resource| resource.compute_md5 }

  class << self
    # This would define top-level meta entries
    meta :total_count do |context|
      # apply filters and get the count
    end
  end

  has_many :book_comments
end
```

Additionally, the serializer will need access to the context in order to perform certain types of queries (ie: getting the total count).  Currently, the serializer is not privy to the filters that generated the query and only has access to the array of records.

**Comment by lgebhardt** [comment]
Thanks for starting this. This feature has been added, though slightly differently, in other PRs.

**Pull request closed without merging**
