### PR TITLE
Add associated_records method to enable override.

### PR DESCRIPTION
**Pull request by barelyknown**
This implements the idea that we discussed in issue https://github.com/cerebris/jsonapi-resources/issues/108. I made the `associated_records` method similar to the `records` method as @lgebhardt suggested and I think that it works nicely and is clear.

### CODE REVIEW

**Comment by lgebhardt** [comment]
A single `associated_records` could become unwieldy with a lot of associations, all with different permissions systems. I'd rather we went with one method for each association. That could be created in the `_associate` method only if it isn't already defined in the resource. The only downside I see is the user would need to know to create the method with a certain name, so documentation is important.

I guess another option is to allow the user to specify the name when the association is defined.

**Comment by barelyknown** [comment]
It seems more unwieldy to me to have one method for each association in most situations. I would guess that the most common case would be something similar to what I'm doing:

``` ruby
class BaseResource < JSONAPI::Resource
  def associated_records(association_name, options = {})
    associated_records = model.public_send(association_name)
    current_user = options[:context][:current_user]
    controller = options[:context][:controller]
    permission = controller.action_name + "?"

    case associated_records.class
    when ActiveRecord::Relation, Array
      associated_records = Pundit.policy_scope!(current_user, associated_records)
      controller.policy_scoped!
    when NilClass
      controller.policy_authorized!
    else
      policy = Pundit.policy!(current_user, associated_records)
      unless policy.public_send(permission)
        error = Pundit::NotAuthorizedError.new("not allowed to #{permission} this #{associated_records}")
        error.query, error.record, error.policy = permission, associated_records, policy
        raise error
      end
      controller.policy_authorized!
    end
    associated_records
  end
end
```

If you need to implement a different approach for a resource class or for a relationship in a resource, you could override at a lower level.

Finally, I'd like to limit the metaprogramming the definition of methods where we can. It's fine where it's needed, but I don't think that this situation warrants it.

**Comment by dgeb** [comment]
Since association and attribute values can already be overridden with meta-programming, I think @lgebhardt's suggestion is consistent.

For example:

``` ruby
class AuthorResource < JSONAPI::Resource
  attribute :id, :name

  has_many :posts

  def name(options)
    @model.name.capitalize
  end

  def posts(options)
    // return sorted, filtered, paginated posts
  end

  def posts_records(options)
    // return raw set of models
  end
end
```

How about chaining both approaches, wherein the meta-method (`posts_records` in this case) calls `associated_records` by default.

**Comment by barelyknown** [comment]
I think that having the meta-method return the `associated_records` by default would be ok. I still don't exactly see the need to generate the meta-methods TBH, but as long as there is a default `associated_records` and you see it as important, it's fine with me.

**Comment by barelyknown** [comment]
If we're good with that approach, I can update the PR. Let me know.

**Comment by lgebhardt** [comment]
I'm good with that. Thanks, @barelyknown

**Comment by barelyknown** [comment]
For `has_one` relationships, do you think that the method should be `post_record` or `post_records` (for example)? `post_record` feels right to me.

**Comment by lgebhardt** [comment]
I agree the singular feels right. However it is still returning an ActiveRecord relation, same as the has_many, so maybe we should still go with the plural? @dgeb any thoughts?

**Comment by dgeb** [comment]
How about `records_for_posts` (has-many) and `record_for_author` (has-one)?

**Comment by lgebhardt** [comment]
:+1:

**Comment by barelyknown** [comment]
I implemented our decision and renamed `associated_records` to `records_for` which is good and more consistent with the `records` method name. Good suggestions. This turned out right.

**Comment by dgeb** [comment]
@barelyknown thanks for following through! Glad those naming suggestions worked for you. And I agree that `records_for` is nice and consistent.

**Comment by lgebhardt** [comment]
Looks good. Thanks!

**Pull request merged**
