### PR TITLE
Fix inherited pagination

### LINKED ISSUE #1063: Methods on base resource not called on subclass
```ruby
class API::V1::ServicesBaseResource < JSONAPI::Resource
  abstract

  key_type :uuid
  paginator :none
end

class API::V1::DashboardResource < API::V1::ServiceBaseResource
  model_name 'Services::Dashboard'
end
```

## Expectation

That `API::V1::DashboardResource` has `paginator` set to **:none**.

## What happens

`offset` and `limit` are still getting called on the dashboard resource.

## Workaround

Call `paginator :none` from the subclass

```ruby
class API::V1::DashboardResource < API::V1::ServiceBaseResource
  model_name 'Services::Dashboard'

  paginator :none
end
```

### PR DESCRIPTION
**Pull request by Exelord**
This PR will fix https://github.com/cerebris/jsonapi-resources/issues/1063

### CODE REVIEW

**Comment by Exelord** [comment]
@lgebhardt ^^

**Comment by lgebhardt** [comment]
@Exelord I've restarted the Travis build. Code looks ok to me.

**Comment by Exelord** [comment]
Passed! 👍

**Comment by Exelord** [comment]
@lgebhardt Is it ready to merge now?

**Comment by lgebhardt** [comment]
Merged by #1102

**Pull request closed without merging**
