### PR TITLE
Allow whitelisted errors from controller to raise

### LINKED ISSUE #569: Exception whitelist not working in 0.7.0, but is fine on 0.6.2
I have a compound 3 field unique index in postgresql, that raises PG::UniqueViolation which is properly translated to ActiveRecord::RecordNotUnique.

Using config.exception_class_whitelist = [ActiveRecord::RecordNotUnique] in 0.6.2, i can properly handle it in the controller with 'rescue_from'.
However in 0.7.0 i get 500 internal server error, indicating that is handled internally bypassing the whitelist in the initializer.

### PR DESCRIPTION
**Pull request by lgebhardt**
Fixes #569

### CODE REVIEW

**Comment by brandonparsons** [comment]
:rainbow:

**Comment by ioagel** [comment]
Great @lgebhardt

**Comment by oliverbarnes** [comment]
:+1: (was just bitten by #569)

**Comment by acid** [comment]
Please merge it! :)

**Comment by john-griffin** [comment]
Just hit this too.

**Comment by joshuaclayton** [comment]
Woohoo; just hit this as well. Thanks @lgebhardt!

**Pull request merged**
