### PR TITLE
Works around primary key being cast due to pluck bug

### PR DESCRIPTION
**Pull request by butchmarshall**
### All Submissions:

- [X] I've checked to ensure there aren't other open [Pull Requests](https://github.com/cerebris/jsonapi-resources/pulls) for the same update/change.
- [X] I've submitted a [ticket](https://github.com/cerebris/jsonapi-resources/issues) for my issue if one did not already exist.
- [X] My submission passes all tests. (Please run the full test suite locally to cut down on noise from travis failures.)
- [X] I've used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message or the description.
- [X] I've added/updated tests for this change.

### Bug fixes and Changes to Core Features:

- [X] I've included an explanation of what the changes do and why I'd like you to include them.
- [X] I've provided test(s) that fails without the change.

### Test Plan:

A unit test has been included with this pull request which reproduces the issue described.

### Reviewer Checklist:
- [X] Maintains compliance with JSON:API
- [X] Adequate test coverage exists to prevent regressions

This fixes issue #1156 and provides a complete set of fixes for pull request #986.

### CODE REVIEW

**Review by lgebhardt — CHANGES_REQUESTED** [review]
Thanks for the fix. Could you please rework the tests so this passes on rails 4.2?

**Comment by butchmarshall** [comment]
Can do.  It may take me a day or so but it'll definitely get done. Thanks!

**Comment by butchmarshall** [comment]
Looks like it's failing because I added a `key_type :uuid` JSONAPI::Resource test (none had existed before).

Most likely related to https://github.com/rails/rails/issues/24857

Workaround is to set self.primary_key = "id" on the resource.

I've pushed a fix (note my commenting out of the final assert_equal in my new test)

**Comment by lgebhardt** [comment]
@butchmarshall Thanks for tracking that down and fixing!

**Pull request merged**
