### PR TITLE
Changing the words from creatable to createable

### PR DESCRIPTION
**Pull request by adomokos**
Throughout the code the word "createable" is used.

### CODE REVIEW

**Comment by lgebhardt** [comment]
Thanks!

**Comment by dgeb** [comment]
Obviously, we need the README to match the code, but after a quick Google search I don't think that either `updateable` or `createable` are correct in British or American English. We should probably deprecate both usages in favor of `updatable` and `creatable`.

**Comment by lgebhardt** [comment]
I had to check, but you seem to be right. I'll put a PR together to fix those mistakes and deprecate the existing methods.

**Comment by adomokos** [comment]
:+1: for "creatable".

**Comment by dgeb** [comment]
Thanks @lgebhardt :+1:

**Comment by barelyknown** [comment]
I'd like to see deprecation warnings on the current methods for a while especially since many projects are probably currently tied to the master branch. No need to break implementations without some warning. I think that was @dbeg's recommendation, but I just wanted to make sure.

**Comment by lgebhardt** [comment]
@barelyknown, I agree.

**Comment by adomokos** [comment]
@dgeb and @lgebhardt: I submitted a [PR](https://github.com/cerebris/jsonapi-resources/pull/245) for this.

**Comment by dbeg** [comment]
@barelyknown: That wasn't my recommendation, but it's still a good idea...

**Comment by dgeb** [comment]
Terrible news for dyslexics: @dbeg and @dgeb are working on the same project :fearful:

On the other hand, it could be good news for me if @dbeg is a robotic alter ego who's come to help me out with this mountain of open source :stuck_out_tongue:

**Comment by dgeb** [comment]
Apologies for the corny jokes earlier, @dbeg. I now see you were brought here via an inadvertent mention above. Great avatar btw :+1:

**Comment by barelyknown** [comment]
Ha! I'm the guilty party!

**Pull request merged**
