### PR TITLE
Engine Support for Links

### LINKED ISSUE #268: ResourceSerializer#self_href doesn't generate correct links for mounted engines
When mounting an engine that uses `jsonapi-resources` to a custom folder like so:

``` ruby
Rails.application.routes.draw do
  mount Basechurch::Engine => "/api"
end
```

All my links are not taking into account the custom folder when generated.

When hitting the following endpoint:

`GET http://example.com/api/v1/bulletins/2`

My response looks like so:

``` json
{
    "data": {
        "id": "2",
        "type": "bulletins",
        "links": {
            "self": "http://example.com/basechurch/v1/bulletins/2"
        }
        ...
    }
}
```

I'm pretty sure the issue is that the `ResourceSerializer` doesn't take into account mountable paths when formatting module names in resource class names: https://github.com/cerebris/jsonapi-resources/blob/4e46ed00606440f7136b041a6ead4c8353bc4a4b/lib/jsonapi/resource_serializer.rb#L215. Is this out of scope for the `ResourceSerializer`? Should I create a `MountedEngineResourceSerializer` for myself?

### PR DESCRIPTION
**Pull request by thewatts**
This is a WIP, will update when ready to merge.
- [x] Spiked Functionality
- [x] Tests
- [x] Refactor

---

This will fix #268

### CODE REVIEW

**Comment by lgebhardt** [comment]
:+1: I like the direction this is going.

**Comment by thewatts** [comment]
@lgebhardt this is ready for review :grin: 
( well, assuming the CI builds pass :sweat_smile: )

**Comment by lgebhardt** [comment]
Thanks @thewatts It looks good, but I haven't tried it in an actual app yet. I would like to know if this works in @achan's project too.

**Comment by courtsimas** [comment]
+1

**Comment by achan** [comment]
All specs passing on my side when I swap in your branch. Great job @thewatts :+1:

**Comment by lgebhardt** [comment]
Great job @thewatts! Thanks for checking @achan.

**Comment by thewatts** [comment]
Wooo! Thanks @lgebhardt && @achan ! :D

**Pull request merged**
