### PR TITLE
Added preliminary support for Rails 3.2 - not for merging

### PR DESCRIPTION
**Pull request by jamonholmgren**
Tests are not passing, but I have successfully gotten this gem to work on Rails 3.2 (at least GET and POST requests, which are what I've tested so far).

I added an ugly polyfill file and started to work on the tests, but haven't made it too far on that.

I'd recommend not merging this pull request, but if someone else needs Rails 3.2 support, they can use my fork:

``` ruby
gem "jsonapi-resources", github: "jamonholmgren/jsonapi-resources", branch: "rails-32-support"
```

If you want to keep this PR open so people can see it, that would probably be good. Up to you though.

### CODE REVIEW

**Comment by jamonholmgren** [comment]
I'll try to keep this branch up to date with `master`.

**Comment by jamonholmgren** [comment]
Tests pass, but only if you don't test against 3.2. Maybe that's okay.

**Comment by scrogson** [comment]
Maintainers: would love to know if this PR is even being considered? I'm working on a Rails 3.2 codebase and would love to see backwards compatibility if possible. Totally understand if not.

**Comment by lgebhardt** [comment]
No, we haven't actively been considering adding support for Rails 3. I don't know if @jamonholmgren has been keeping his branch up to date. This PR wasn't merged because tests didn't pass for Rails 3.2.

I am not at all opposed to Rails 3 support if someone wants to make a PR that doesn't cripple the existing features (or gracefully excludes incompatible ones), adds Rails 3.x to the testing matrix, and passes all the existing tests. I'm not sure what that would take, but it's a bit more than I want to bite off myself at this point.

**Comment by scrogson** [comment]
@lgebhardt great to hear. Thank you for the response.

@jamonholmgren do you have the bandwidth to get this PR up to par for 3.x?

**Comment by jamonholmgren** [comment]
Hey @scrogson ,

I won't be updating this branch as we're not using it anymore. We ended up bringing our Rails app up to 4.2 and abandoning jsonapi-resources in favor of the more mainstream [active_model_serializers](https://github.com/rails-api/active_model_serializers), which is Rails 4+ only.

I do know that this branch worked pretty well on Rails 3.2. You'll need to merge in latest master and ensure there are no conflicts. Basically, I shimmed various things (like Hash) to have Rails 4 methods that jsonapi-resources was relying on. It's a quick & dirty way to accomplish the goal, but that's what I needed at the time.

**Comment by vrybas** [comment]
Can this PR be closed then? Supporting 3.x doesn't seem like a good 
idea, when 5.x is around the corner :)

**Comment by jamonholmgren** [comment]
:+1:

**Pull request closed without merging**
