### PR TITLE
Added pagination GET examples in README

### PR DESCRIPTION
**Pull request by coryodaniel**
Silly PR, but I didn't understand the docs regarding pagination and had to peek at the implementation to figure it out. Maybe I'm dumb, but any who, added an example for GETting paginated resources.

### CODE REVIEW

**Comment by utilityboy** [comment]
Hi @coryodaniel .  I've put together a list of list of examples here:

https://github.com/cerebris/jsonapi-resources/wiki/JSONAPI::Resources-Querystring-Examples

Perhaps @lgebhardt we should link to this somewhere in the readme?

**Comment by lgebhardt** [comment]
@coryodaniel Thanks, that should help.

**Comment by lgebhardt** [comment]
@bjubinville Thanks for putting that page together. A link to the Wiki page would certainly be helpful, but I'm starting to reconsider the use of the Wiki. At some point I'd like to refactor the long Readme into separate `docs` pages and move a lot of the wiki content into that. I get the feeling people don't think to check the wiki.

**Comment by utilityboy** [comment]
@lgebhardt I'm happy to create a PR for the README and pull those examples inline where appropriate until you guys have determined how you'd like to structure things.  Also happy to contribute to documentation etc as well if you'd like help pulling things together.

**Pull request merged**
