### PR TITLE
Moar Rails5 compatibility

### PR DESCRIPTION
**Pull request by nathanpalmer**
# Overview

This brings in Rails 5 compatibility for every feature we're currently using. This is spiked out on an app we're likely going to production in the next few weeks. We haven't found any new issues the last week or so.
# Reasoning

I realize there are already multiple rails 5 pull requests out there but none of them worked for us 100% and the lack of movement on any of them led us to create a new one off of a more recent master. 
- https://github.com/cerebris/jsonapi-resources/pull/579
- https://github.com/cerebris/jsonapi-resources/pull/469
- https://github.com/cerebris/jsonapi-resources/pull/593

I'm going to try and cover what changes were made to this and why and I'd love to feedback on what the Rails 5 plan is going forward. Personally I'd love this, or the others to get pulled in so we can work off of an official release versus a branch.
# Changes for Rails 5 compatibility
- [x] Unable to modify 'Content-Type' as part of the ensure on `process_request` because headers have already been sent.
- [x] `ActionDispartch::ParamsParser` was moved to `ActionDispatch::Http::Parameters`
- [x] All levels of params [are now of type ActionController::Parameters](http://eileencodes.com/posts/actioncontroller-parameters-now-returns-an-object-instead-of-a-hash/) instead of a hash
- [x] Unable to modify `@scope` instead you must instantiate a new scope in the linked list

### CODE REVIEW

**Comment by ovelar** [comment]
:+1:

**Comment by lgebhardt** [comment]
Thanks for this. This looks like a manageable set of changes. Most tests are broken, but I've started fixing them to work with the changes you have here. So far the changes seem fairly minor.

**Comment by nathanpalmer** [comment]
@lgebhardt Awesome! (I should have checked the tests.) Let me know if I can jump in there and help out with that. Sounds like you're already in there doing it.

**Comment by lgebhardt** [comment]
@nathanpalmer I've added a branch named `rails5` which contains your code changes and alters the tests to work with both Rails 4 and 5. I will keep this branch up to date with new changes to master.

If you have more changes for Rails 5 please make a separate PR into the `rails5` branch.

**Comment by nathanpalmer** [comment]
@lgebhardt That's great! We'll switch over to that branch for our app and see if we run into anything else.

**Comment by kirantpatil** [comment]
How should we use Rails 5 branch version of Jsonapi-resources in our application to test it ? We are planning to use Rails 5 api and Jsonapi-resources.

**Comment by vrybas** [comment]
@kirantpatil, use `branch:` option in Gemfile:

``` ruby
gem 'jsonapi-resources', git: 'https://github.com/cerebris/jsonapi-resources.git',
                         branch: 'rails5'
```

**Comment by kirantpatil** [comment]
Thank you Sir.

**Pull request merged**
