### PR TITLE
Refactor request to support custom operations

### PR DESCRIPTION
**Pull request by hinshun**
Addresses #330.

### CODE REVIEW

**Comment by hinshun** [comment]
Opted for refactoring `JSONAPI::FindOperation` out of the JSONAPI namespace, etc, to stay consistent with the `def class_for(type)` you have in other classes. Otherwise I will have to do something like:

``` ruby
def resource_operation_for(resource_klass, operation)
  # ...
  resource_operation || Operation.operation_for("JSONAPI/#{operation}")
end
```

The master branch's specs are passing atm, so if this looks like the right approach I will write specs next.

**Comment by lgebhardt** [comment]
@hinshun I think this a good approach. It might be nice to take it even farther and move the Operation setup logic from the request to the Operations themselves (initialize taking the request object, which could contain just common parsing logic). Then the correct operation could be defined on the route, or probably better each resource could map an action to an operation (could use the context to choose the correct operation). But either way would allow you to create your custom operations without altering the request class. It would also remove a lot of the code smell from Request class, which has been on my to do list.

How are you assigning your new operations to actions?

**Comment by hinshun** [comment]
@lgebhardt Could you clarify what you mean by `resource could map an action to an operation`? I'm not sure what `action` means in the context of this gem. Do you mean to move the setup_.*_action methods into the resource class?

You can override existing operations like so:

``` ruby
class EventCreateResourceOperation < CreateResourceOperation
  def apply
    # ...
    resource.my_method!
    # ...
    return JSONAPI::ResourceOperationResult.new((result == :completed ? :created : :accepted), resource)

  rescue JSONAPI::Exceptions::Error => e
    return JSONAPI::ErrorsOperationResult.new(e.errors[0].code, e.errors)
  end

  end
end
```

`Operation.resource_operation_for(resource_klass, operation)` will first search for a operation with the `resource_klass` in the front before defaulting the the base operation.

Though with this, we can refactor it so that we don't override `apply`, so that returning the result wrapper and catching the exception can be handled by the base operation class.

**Comment by lgebhardt** [comment]
@hinshun I was thinking we move the setup_.*_action methods into the operations themselves. There might be some issues here with supporting multiple operations per request which we should consider.

The way it works currently is the `action` comes in from the controller (and is set by the route). The controller creates the `request` object which uses the action to know which operations to create, and initializes them. 

What I was trying to understand is where your new operations are being created and how the code knows to use EventCreateResourceOperation instead of CreateResourceOperation. I had missed that it was in prepending the resource name to the operation.

What I was proposing was allowing the resource to control which operations are used for each action. The advantage I see to this approach is you could override one of the operations and use it for more than one resource without needing to declare an operation per resource (which I know I would be prone to doing).

**Comment by hinshun** [comment]
@lgebhardt I see what you mean now. Regarding multiple operations per request, in what scenario would you need to support a 1:n relationship? I think in that case you could write an operation that uses other smaller operations so that the relationship remains 1:1.

I agree with decoupling the operations from a specific resource, but I wonder if you could delve into why it should live in the resource vs its respective controller?

**Comment by lgebhardt** [comment]
@hinshun When support for batch requests are added to JSON API we will want to extend JR to handle those. There may be other instances where a request will map to multiple operations.

The main reason I see adding it to the resource and not the controller is that maybe when we support some JSON API extensions, such as Batch, a request will need to have Operations for multiple different resource types.

**Pull request closed without merging**
