### PR TITLE
provide fields parameter from request to operation

### PR DESCRIPTION
**Pull request by senid231**
it allows for example to do something like:

``` ruby
class CatResource < JSONAPI::Resource
  attributes :name, :breed

  filters :name

  def self.records(options = {})
    fields = options.fetch(:fields, {})[:cats]
    coll = super
    fields.nil? ? coll : coll.select(fields.join(','))
  end

end
```

``` ruby
class ExtendedMetaOperationsProcessor < ActiveRecordOperationsProcessor

  after_find_operation do
    @operation_meta[:fields] = @operation.fields
  end

end
```

### CODE REVIEW

**Comment by senid231** [comment]
any updates about this?

**Comment by lgebhardt** [comment]
@senid231 Sorry, merging #694 created a few conflicts with this. Could you rework this to work with the new changes?

**Comment by senid231** [comment]
done

**Comment by lgebhardt** [comment]
@senid231 Thanks!

**Pull request merged**
