### PR TITLE
filtering of included resources is now available. Caching doesn't wor…

### PR DESCRIPTION
**Pull request by beniutek**
…k when we do this and needs to be turned off though

In future will look into caching and check what options are there to make it available

### CODE REVIEW

**Comment by beniutek** [comment]
this is a new feature in response of issue #890 that was created by me

**Comment by santostiago** [comment]
Is this going to be merged? For me it's a really handy feature!

**Comment by dolan** [comment]
This is kind of an important feature. Do you need a volunteer to resolve conflicts? What's missing here?

**Comment by carlthuringer** [comment]
This pull request is in pretty bad shape, with partially-completed features and a scattering of random changes and dead ends. There's no way to integrate it with 0.10 beta. I was able to clean it up and integrate it to 0.9 but I am not sure if anybody wants a PR against 0.9 with this feature. @hatchloyalty has a fork with a couple of improvements to 0.9.

**Pull request closed without merging**
