### PR TITLE
Fix  polymorphism with custom key name issue

### PR DESCRIPTION
**Pull request by brcebn**
### All Submissions:

- [x] I've checked to ensure there aren't other open [Pull Requests](https://github.com/cerebris/jsonapi-resources/pulls) for the same update/change.
- [x] I've submitted a [ticket](https://github.com/cerebris/jsonapi-resources/issues) for my issue if one did not already exist.
- [x] My submission passes all tests. (Please run the full test suite locally to cut down on noise from travis failures.)
- [x] I've used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message or the description.
- [ ] I've added/updated tests for this change.

### New Feature Submissions:

- [x] I've submitted an issue that describes this feature, and received the go ahead from the maintainers.
- [ ] My submission includes new tests.
- [x] My submission maintains compliance with [JSON:API](http://jsonapi.org/).

### Bug fixes and Changes to Core Features:

- [x] I've included an explanation of what the changes do and why I'd like you to include them.
- [ ] I've provided test(s) that fails without the change.

### Reviewer Checklist:
- [ ] Maintains compliance with JSON:API
- [ ] Adequate test coverage exists to prevent regressions

### CODE REVIEW

**Comment by lgebhardt** [comment]
@benebrice Please rebase your branch against the latest 0.9 changes. That should fix the travis build issues.

**Comment by brcebn** [comment]
@lgebhardt The latest changes it on the branch `release-0-9` right?

**Comment by lgebhardt** [comment]
@benebrice Sorry, I hadn't updated the travis build for the release-0-9 branch. If you rebase now your branch should build.

**Comment by brcebn** [comment]
@lgebhardt Travis build running.

By the way, I haven't added test for this case. I spent too much of my time to try to add one. I though maybe to have a clue to add this little one?

**Comment by brcebn** [comment]
@lgebhardt It seems that Travis is blocked. Is it possible to just restart it?

**Comment by lgebhardt** [comment]
@benebrice Thanks! I rebased and merged.

**Pull request closed without merging**
