### PR TITLE
Some patches to support Rails 5 (WIP)

### LINKED ISSUE #466: Rails 5 Support?
Is anyone working on Rails 5 support for JR? I just tried it out and it's got a few problems due to using some of Rails' internal API. The two that I've hit so far are that `ActionDispatch::ParamsParser::DEFAULT_PARSERS` is no longer a thing so mime_types.rb explodes and `@scope[:jsonapi_resource] = @resource_type` no longer works (the `[]=` setter was removed by @tenderlove 10 days ago or so).

I've got a fork where I'm working on fixing some of these problems but was curious if anyone else has already started down this path?

### PR DESCRIPTION
**Pull request by jashank**
While Rails 5 is still evolving towards a release check, catch some of the breaking changes and patch them.  It's not yet perfectly ready to merge, though, especially as this chases a moving target.

This doesn't seem to cause issues with Rails 4._x_ support.

Fixes #466.
Obsoletes #384.

### CODE REVIEW

**Comment by jashank** [comment]
(Ah, hey, thanks, Emacs, for adding a `coding: utf-8` line with no good reason. Much appreciated.)

**Comment by lgebhardt** [comment]
Thanks. Good to see the number of changes are fairly small.

**Comment by olivierlacan** [comment]
@jashank Could you rebase this and fix the conflicts? Seems like this needs to be merged for actual Rails 5 compatibility and still hasn't be addressed on master AFAICT.

**Comment by olivierlacan** [comment]
Never mind, I'm wrong. This is fixed on master. I think this PR can be closed.

**Comment by jashank** [comment]
Blimey, this is ancient. I assume this is now fixed elsewhere; closing.

**Pull request closed without merging**
