### PR TITLE
Request options

### PR DESCRIPTION
**Pull request by lgebhardt**
This extends #351 and implements the feature in different manner.

### CODE REVIEW

**Comment by koppen** [comment]
`allowed_request_params` is still referenced in the configuration part of the README (which is where I originally noticed it). I'd be happy to update the README, but I don't think I could push the changes to this pull request.

**Comment by lgebhardt** [comment]
@koppen I don't see it. Are you sure? Maybe you're looking at the master branch? Maybe I'm blind :)

**Comment by koppen** [comment]
Doh, nevermind me, I was looking at master, of course

**Comment by lgebhardt** [comment]
Glad that was it. Thanks!

**Pull request merged**
